// Fixture rows for `pnpm db:seed`. Stage / job type / experience are referenced by their
// seeded position (see src/db/defaults.ts) because names are user-renamable.
// Dates are day offsets from "today" so the dataset keeps exercising due/stale KPIs
// whenever the seed is re-run. See docs/reference/seed-data.md

type SeedOpportunity = {
  stagePosition: number
  jobTypePosition: number | null
  experiencePosition: number | null
  recruiter: string
  esn: string | null
  endClient: string | null
  need: string | null
  dailyRate: number | null
  onsiteDays: number | null
  location: string | null
  lastContactOffset: number | null
  nextReminderOffset: number | null
  phone: string | null
  offerUrl: string | null
  notes: string | null
  isPinned: boolean
  isArchived: boolean
}

// 24 rows = 3 pages at the default page size of 8.
export const SEED_OPPORTUNITIES: readonly SeedOpportunity[] = [
  {
    stagePosition: 3,
    jobTypePosition: 0,
    experiencePosition: 2,
    recruiter: 'Camille Ferrand',
    esn: 'Sopra Steria',
    endClient: 'Société Générale',
    need: 'Refonte du portail client React / Node',
    dailyRate: 620,
    onsiteDays: 2,
    location: 'Paris 13e',
    lastContactOffset: -2,
    nextReminderOffset: 0,
    phone: '+33 6 12 44 87 903',
    offerUrl: 'https://www.free-work.com/fr/tech-it/offre/fullstack-societe-generale',
    notes: 'Second entretien technique prévu. Préparer le cas pratique sur le cache Redis.',
    isPinned: true,
    isArchived: false
  },
  {
    stagePosition: 4,
    jobTypePosition: 0,
    experiencePosition: 2,
    recruiter: 'Yanis Boucher',
    esn: null,
    endClient: 'Doctolib',
    need: 'Squad paiement — TypeScript / Postgres',
    dailyRate: 700,
    onsiteDays: 1,
    location: 'Levallois-Perret',
    lastContactOffset: -1,
    nextReminderOffset: 3,
    phone: '+33 7 81 20 55 14',
    offerUrl: 'https://careers.doctolib.com/offre/fullstack-payments',
    notes: 'Proposition reçue à 700 €. Négocier le 100 % remote un vendredi sur deux.',
    isPinned: true,
    isArchived: false
  },
  {
    stagePosition: 2,
    jobTypePosition: 1,
    experiencePosition: 1,
    recruiter: 'Inès Lemoine',
    esn: 'Capgemini',
    endClient: 'Orange Business',
    need: 'Design system Angular 18',
    dailyRate: 520,
    onsiteDays: 3,
    location: 'Rennes',
    lastContactOffset: -9,
    nextReminderOffset: null,
    phone: '+33 6 74 09 31 62',
    offerUrl: null,
    notes: 'CV transmis au client final, retour annoncé sous dix jours.',
    isPinned: false,
    isArchived: false
  },
  {
    stagePosition: 1,
    jobTypePosition: 2,
    experiencePosition: 2,
    recruiter: 'Thomas Vasseur',
    esn: 'Devoteam',
    endClient: 'EDF',
    need: 'API Java / Spring Boot pour la supervision réseau',
    dailyRate: 580,
    onsiteDays: 2,
    location: 'Saint-Denis',
    lastContactOffset: -12,
    nextReminderOffset: null,
    phone: '+33 6 33 78 40 21',
    offerUrl: 'https://www.linkedin.com/jobs/view/backend-edf-3928471',
    notes: 'Relancé une fois, pas de réponse depuis. Prévoir un dernier message.',
    isPinned: false,
    isArchived: false
  },
  {
    stagePosition: 0,
    jobTypePosition: 4,
    experiencePosition: 1,
    recruiter: 'Sarah Kaci',
    esn: null,
    endClient: 'Qonto',
    need: 'Platform engineer — Kubernetes / Terraform',
    dailyRate: 650,
    onsiteDays: 1,
    location: 'Paris 2e',
    lastContactOffset: null,
    nextReminderOffset: null,
    phone: null,
    offerUrl: 'https://qonto.com/en/careers/platform-engineer',
    notes: 'Offre repérée sur Welcome to the Jungle, pas encore contacté.',
    isPinned: false,
    isArchived: false
  },
  {
    stagePosition: 1,
    jobTypePosition: 0,
    experiencePosition: 2,
    recruiter: 'Grégoire Aubert',
    esn: 'Astek',
    endClient: 'Thales Avionics',
    need: 'Outil interne de suivi de production',
    dailyRate: 545,
    onsiteDays: 4,
    location: 'Mérignac',
    lastContactOffset: -4,
    nextReminderOffset: 2,
    phone: '+33 5 56 12 90 44',
    offerUrl: null,
    notes: 'Habilitation défense demandée, délai de trois semaines.',
    isPinned: false,
    isArchived: false
  },
  {
    stagePosition: 3,
    jobTypePosition: 3,
    experiencePosition: 1,
    recruiter: 'Léa Marchand',
    esn: null,
    endClient: 'BlaBlaCar',
    need: 'React Native — refonte du tunnel de réservation',
    dailyRate: 600,
    onsiteDays: 2,
    location: 'Paris 9e',
    lastContactOffset: -3,
    nextReminderOffset: -1,
    phone: '+33 6 45 88 12 07',
    offerUrl: 'https://blablacar.com/jobs/mobile-engineer',
    notes: 'Entretien avec le lead mobile passé, en attente du retour RH.',
    isPinned: false,
    isArchived: false
  },
  {
    stagePosition: 2,
    jobTypePosition: 5,
    experiencePosition: 2,
    recruiter: 'Nicolas Perrin',
    esn: 'Talan',
    endClient: 'Carrefour',
    need: 'Pipelines dbt / BigQuery pour le retail media',
    dailyRate: 610,
    onsiteDays: 2,
    location: 'Massy',
    lastContactOffset: -6,
    nextReminderOffset: null,
    phone: '+33 6 21 77 34 58',
    offerUrl: null,
    notes: 'Dossier de compétences envoyé, shortlist de trois profils.',
    isPinned: false,
    isArchived: false
  },
  {
    stagePosition: 1,
    jobTypePosition: 1,
    experiencePosition: 0,
    recruiter: 'Manon Rivière',
    esn: 'Alten',
    endClient: 'Airbus',
    need: 'Vue 3 — dashboards de maintenance',
    dailyRate: 430,
    onsiteDays: 5,
    location: 'Toulouse',
    lastContactOffset: -15,
    nextReminderOffset: null,
    phone: '+33 5 61 44 20 18',
    offerUrl: 'https://www.alten.fr/offres/frontend-vue-airbus',
    notes: 'TJM sous ma référence et 5 jours sur site, peu prioritaire.',
    isPinned: false,
    isArchived: false
  },
  {
    stagePosition: 0,
    jobTypePosition: 0,
    experiencePosition: 2,
    recruiter: 'Julien Delaunay',
    esn: null,
    endClient: 'Alan',
    need: 'Fullstack TypeScript — équipe santé',
    dailyRate: 680,
    onsiteDays: 0,
    location: 'Full remote',
    lastContactOffset: null,
    nextReminderOffset: null,
    phone: null,
    offerUrl: 'https://alan.com/careers/fullstack-engineer',
    notes: '100 % remote, à contacter via cooptation de Marc.',
    isPinned: true,
    isArchived: false
  },
  {
    stagePosition: 2,
    jobTypePosition: 2,
    experiencePosition: 1,
    recruiter: 'Fatou Ndiaye',
    esn: 'Onepoint',
    endClient: 'Ministère de l’Intérieur',
    need: 'Migration Symfony 6 vers une architecture hexagonale',
    dailyRate: 560,
    onsiteDays: 3,
    location: 'Paris 15e',
    lastContactOffset: -8,
    nextReminderOffset: 1,
    phone: '+33 1 44 62 08 90',
    offerUrl: null,
    notes: 'Marché public, démarrage conditionné à la notification.',
    isPinned: false,
    isArchived: false
  },
  {
    stagePosition: 1,
    jobTypePosition: 4,
    experiencePosition: 2,
    recruiter: 'Pierre Astier',
    esn: 'Ippon Technologies',
    endClient: 'Decathlon',
    need: 'Migration AWS et industrialisation CI/CD',
    dailyRate: 640,
    onsiteDays: 1,
    location: 'Lille',
    lastContactOffset: -5,
    nextReminderOffset: null,
    phone: '+33 6 09 55 71 33',
    offerUrl: 'https://www.ippon.fr/offres/devops-decathlon',
    notes: 'Bon feeling au téléphone, ils reviennent vers moi cette semaine.',
    isPinned: false,
    isArchived: false
  },
  {
    stagePosition: 3,
    jobTypePosition: 0,
    experiencePosition: 2,
    recruiter: 'Hélène Barbier',
    esn: null,
    endClient: 'Payfit',
    need: 'Squad core — Node / React',
    dailyRate: 660,
    onsiteDays: 2,
    location: 'Paris 8e',
    lastContactOffset: -7,
    nextReminderOffset: -2,
    phone: '+33 6 88 41 26 70',
    offerUrl: 'https://payfit.com/careers/senior-fullstack',
    notes: 'Relance à faire, le retour promis n’est jamais arrivé.',
    isPinned: false,
    isArchived: false
  },
  {
    stagePosition: 0,
    jobTypePosition: 1,
    experiencePosition: 1,
    recruiter: 'Antoine Gérard',
    esn: 'Zenika',
    endClient: 'La Poste',
    need: 'Front React sur le suivi de colis',
    dailyRate: 505,
    onsiteDays: 2,
    location: 'Nantes',
    lastContactOffset: null,
    nextReminderOffset: null,
    phone: null,
    offerUrl: null,
    notes: null,
    isPinned: false,
    isArchived: false
  },
  {
    stagePosition: 2,
    jobTypePosition: 0,
    experiencePosition: 2,
    recruiter: 'Claire Fontaine',
    esn: 'Accenture',
    endClient: 'AXA',
    need: 'Portail courtier — micro-frontends',
    dailyRate: 590,
    onsiteDays: 3,
    location: 'Nanterre',
    lastContactOffset: -11,
    nextReminderOffset: null,
    phone: '+33 1 53 23 44 12',
    offerUrl: null,
    notes: 'Process long, quatre étapes annoncées.',
    isPinned: false,
    isArchived: false
  },
  {
    stagePosition: 1,
    jobTypePosition: 5,
    experiencePosition: 1,
    recruiter: 'Mehdi Cherif',
    esn: 'Keyrus',
    endClient: 'Sephora',
    need: 'Data engineer — Snowflake / Airflow',
    dailyRate: 575,
    onsiteDays: 2,
    location: 'Neuilly-sur-Seine',
    lastContactOffset: -3,
    nextReminderOffset: 4,
    phone: '+33 6 62 30 98 25',
    offerUrl: 'https://www.keyrus.fr/offres/data-engineer-sephora',
    notes: 'Attente du brief détaillé de la mission.',
    isPinned: false,
    isArchived: false
  },
  {
    stagePosition: 3,
    jobTypePosition: 2,
    experiencePosition: 2,
    recruiter: 'Émilie Roux',
    esn: null,
    endClient: 'Swile',
    need: 'Backend Go — service de titres restaurant',
    dailyRate: 630,
    onsiteDays: 1,
    location: 'Montpellier',
    lastContactOffset: -1,
    nextReminderOffset: 5,
    phone: '+33 6 17 05 63 41',
    offerUrl: 'https://swile.co/careers/backend-go',
    notes: 'Entretien culture fit passé, technique planifié la semaine prochaine.',
    isPinned: false,
    isArchived: false
  },
  {
    stagePosition: 0,
    jobTypePosition: 3,
    experiencePosition: 0,
    recruiter: 'Victor Lambert',
    esn: 'Sqli',
    endClient: 'Fnac Darty',
    need: 'Application mobile Flutter',
    dailyRate: 420,
    onsiteDays: 2,
    location: 'Ivry-sur-Seine',
    lastContactOffset: null,
    nextReminderOffset: null,
    phone: null,
    offerUrl: null,
    notes: 'Stack Flutter, hors de mon cœur de compétence.',
    isPinned: false,
    isArchived: false
  },
  {
    stagePosition: 1,
    jobTypePosition: 0,
    experiencePosition: 2,
    recruiter: 'Sofia Marchetti',
    esn: 'Wavestone',
    endClient: 'BNP Paribas',
    need: 'Plateforme de reporting réglementaire',
    dailyRate: 670,
    onsiteDays: 3,
    location: 'Paris 9e',
    lastContactOffset: -14,
    nextReminderOffset: null,
    phone: '+33 1 49 03 21 76',
    offerUrl: null,
    notes: 'Sans nouvelle depuis deux semaines malgré une relance.',
    isPinned: false,
    isArchived: false
  },
  {
    stagePosition: 2,
    jobTypePosition: 4,
    experiencePosition: 1,
    recruiter: 'Damien Leroy',
    esn: 'Octo Technology',
    endClient: 'Michelin',
    need: 'SRE — observabilité Grafana / Prometheus',
    dailyRate: 600,
    onsiteDays: 2,
    location: 'Clermont-Ferrand',
    lastContactOffset: -6,
    nextReminderOffset: 6,
    phone: '+33 6 51 82 39 04',
    offerUrl: 'https://www.octo.com/offres/sre-michelin',
    notes: 'Dossier en cours de validation côté client.',
    isPinned: false,
    isArchived: false
  },
  {
    stagePosition: 5,
    jobTypePosition: 1,
    experiencePosition: 1,
    recruiter: 'Bruno Sartre',
    esn: 'Umanis',
    endClient: 'Groupama',
    need: 'Front Angular — espace assuré',
    dailyRate: 480,
    onsiteDays: 4,
    location: 'Nanterre',
    lastContactOffset: -21,
    nextReminderOffset: null,
    phone: '+33 1 42 88 55 09',
    offerUrl: null,
    notes: 'Refusé : profil jugé trop orienté React.',
    isPinned: false,
    isArchived: false
  },
  {
    stagePosition: 5,
    jobTypePosition: 0,
    experiencePosition: 2,
    recruiter: 'Aurélie Chevalier',
    esn: null,
    endClient: 'Ledger',
    need: 'Fullstack — outils internes',
    dailyRate: 690,
    onsiteDays: 2,
    location: 'Paris 3e',
    lastContactOffset: -26,
    nextReminderOffset: null,
    phone: '+33 6 94 11 72 38',
    offerUrl: 'https://www.ledger.com/careers/fullstack-internal',
    notes: 'Poste pourvu en interne avant mon entretien final.',
    isPinned: false,
    isArchived: false
  },
  {
    stagePosition: 6,
    jobTypePosition: 2,
    experiencePosition: 1,
    recruiter: 'Kevin Morel',
    esn: 'Expleo',
    endClient: 'SNCF Connect',
    need: 'API Node — moteur de recherche horaires',
    dailyRate: 555,
    onsiteDays: 3,
    location: 'Saint-Ouen',
    lastContactOffset: -34,
    nextReminderOffset: null,
    phone: '+33 6 70 26 84 15',
    offerUrl: null,
    notes: 'Aucune réponse après trois relances.',
    isPinned: false,
    isArchived: false
  },
  {
    stagePosition: 1,
    jobTypePosition: 3,
    experiencePosition: 2,
    recruiter: 'Nadia Belkacem',
    esn: 'Sopra Steria',
    endClient: 'Crédit Agricole',
    need: 'Application mobile Kotlin / Swift',
    dailyRate: 615,
    onsiteDays: 2,
    location: 'Guyancourt',
    lastContactOffset: -18,
    nextReminderOffset: null,
    phone: '+33 1 34 88 12 66',
    offerUrl: null,
    // Archived by the row flag rather than the stage: covers the second archived path.
    notes: 'Mission annulée par le client final, gardée pour l’historique.',
    isPinned: false,
    isArchived: true
  }
] as const
